// ============================================================
// 用語データ（重要単語の意味・カタカナ発音を一元管理）
//
// data.js の各例文の vocabulary は、ここに定義したキーを参照する。
// 同じ単語でも例文によって意味が違う場合は、
// data.js 側で { term: "キー", meaning: "この例文専用の意味" } のように上書きできる。
//
// 新しい単語を追加する時は、ここに1件追記するだけでよい。
// ============================================================

const terms = {
  "permission":    { meaning: "許可・権限",                                   katakana: "パーミッション" },
  "denied":        { meaning: "拒否された（deny の過去分詞）",                  katakana: "デナイド" },
  "such":          { meaning: "そのような",                                   katakana: "サッチ" },
  "directory":     { meaning: "フォルダ（フォルダの技術的な呼び名）",            katakana: "ディレクトリ" },
  "command":       { meaning: "コマンド・命令",                                katakana: "コマンド" },
  "found":         { meaning: "見つかった（find の過去分詞）",                  katakana: "ファウンド" },
  "delete":        { meaning: "削除する",                                     katakana: "デリート" },
  "action":        { meaning: "操作・行動",                                   katakana: "アクション" },
  "undone":        { meaning: "取り消された（undo の過去分詞）",                katakana: "アンダン" },
  "changes":       { meaning: "変更点・差分",                                 katakana: "チェンジズ" },
  "staged":        { meaning: "ステージングされた（コミット準備完了の状態）",     katakana: "ステージド" },
  "commit":        { meaning: "変更を確定して保存すること",                     katakana: "コミット" },
  "working tree":  { meaning: "作業ツリー（現在編集中のファイル群）",            katakana: "ワーキングツリー" },
  "clean":         { meaning: "きれいな・変更なしの状態",                       katakana: "クリーン" },
  "merge":         { meaning: "マージ・統合（2つのブランチを合体させること）",    katakana: "マージ" },
  "conflict":      { meaning: "競合・衝突",                                   katakana: "コンフリクト" },
  "detected":      { meaning: "検出された（detect の過去分詞）",                katakana: "ディテクテッド" },
  "branch":        { meaning: "ブランチ・枝（開発の分岐）",                     katakana: "ブランチ" },
  "up to date":    { meaning: "最新の状態・同期済み",                          katakana: "アップトゥデート" },
  "origin":        { meaning: "リモートリポジトリの別名（通常 GitHub）",         katakana: "オリジン" },
  "pull request":  { meaning: "プルリクエスト（コードのレビュー・統合依頼）",     katakana: "プルリクエスト" },
  "merged":        { meaning: "マージされた・統合された",                       katakana: "マージド" },
  "successfully":  { meaning: "正常に・成功して",                              katakana: "サクセスフリー" },
  "rate limit":    { meaning: "利用制限・レートリミット（単位時間あたりの上限）", katakana: "レートリミット" },
  "exceeded":      { meaning: "超えた・超過した（exceed の過去分詞）",          katakana: "エクシーデッド" },
  "access token":  { meaning: "アクセストークン（認証用の文字列）",              katakana: "アクセストークン" },
  "expired":       { meaning: "期限切れになった（expire の過去分詞）",          katakana: "エクスパイアード" },
  "trust":         { meaning: "信頼する・信用する",                            katakana: "トラスト" },
  "authors":       { meaning: "作成者・著者（author の複数形）",                katakana: "オーサーズ" },
  "unsaved":       { meaning: "保存されていない",                              katakana: "アンセーブド" },
  "lost":          { meaning: "失われた（lose の過去形）",                      katakana: "ロスト" },
  "syntax":        { meaning: "構文・文法（コードのルール）",                    katakana: "シンタックス" },
  "unexpected":    { meaning: "予期しない・予想外の",                           katakana: "アンエクスペクテッド" },
  "token":         { meaning: "トークン（コードの最小単位の記号や単語）",         katakana: "トークン" },
  "properties":    { meaning: "プロパティ・属性（オブジェクトの持つ情報）",       katakana: "プロパティーズ" },
  "undefined":     { meaning: "未定義・値が設定されていない状態",                katakana: "アンディファインド" },
  "extension":     { meaning: "拡張機能（VS Code に追加できる機能）",            katakana: "エクステンション" },
  "incompatible":  { meaning: "互換性がない・相性が悪い",                       katakana: "インコンパティブル" },
  "update":        { meaning: "アップデート・更新",                            katakana: "アップデート" },
  "available":     { meaning: "利用可能な・入手可能な",                         katakana: "アベイラブル" },
  "apply":         { meaning: "適用する",                                     katakana: "アプライ" },
  "session":       { meaning: "セッション（ログイン中の一連の接続期間）",        katakana: "セッション" },
  "invalid":       { meaning: "無効な・不正な",                                katakana: "インバリッド" },
  "credentials":   { meaning: "認証情報（ID やパスワードなど）",                 katakana: "クレデンシャルズ" },
  "allow":         { meaning: "許可する・許す",                                katakana: "アロウ" },
  "run":           { meaning: "実行する・走らせる",                            katakana: "ラン" },
  "matching":      { meaning: "一致する・マッチする",                          katakana: "マッチング" },
  "results":       { meaning: "結果・検索結果",                               katakana: "リザルツ" },
  "connection":    { meaning: "接続・コネクション",                            katakana: "コネクション" },
  "timed out":     { meaning: "タイムアウトした（時間切れになった）",            katakana: "タイムドアウト" },
  "untracked":     { meaning: "追跡されていない・管理されていない",              katakana: "アントラックド" },
  "include":       { meaning: "含める・含む",                                 katakana: "インクルード" },
  "detached":      { meaning: "切り離された・分離された",                       katakana: "デタッチド" },
  "HEAD":          { meaning: "現在チェックアウトしているポイント（Git の用語）", katakana: "ヘッド" },
  "state":         { meaning: "状態",                                        katakana: "ステート" },
  "conversation":  { meaning: "会話・やり取り",                               katakana: "コンバーセーション" },
  "permanently":   { meaning: "永久に・恒久的に",                              katakana: "パーマネントリー" },
  "deleted":       { meaning: "削除された",                                   katakana: "デリーテッド" },
  "limit":         { meaning: "制限・上限",                                   katakana: "リミット" },
  "reached":       { meaning: "達した・到達した（reach の過去形）",             katakana: "リーチト" },
  "fetch":         { meaning: "取得する・取ってくる",                          katakana: "フェッチ" },
  "failed":        { meaning: "失敗した（fail の過去形）",                      katakana: "フェイルド" },
  "push":          { meaning: "プッシュ（ローカルの変更をリモートに送ること）",   katakana: "プッシュ" },
  "repository":    { meaning: "リポジトリ（コードの保管場所）",                  katakana: "リポジトリ" },
  "uncommitted":   { meaning: "未コミットの・まだ確定されていない",              katakana: "アンコミッテッド" },
  "stash":         { meaning: "スタッシュ（変更を一時的に退避させること）",       katakana: "スタッシュ" },
  "overwrite":     { meaning: "上書きする",                                   katakana: "オーバーライト" },
  "existing":      { meaning: "既存の・現在ある",                              katakana: "イグジスティング" },

  // ---- バッチ2: エラーメッセージ編 (2026-06-12 追加) ----
  "module":        { meaning: "モジュール（プログラムの部品・構成要素）",        katakana: "モジュール" },
  "resolve":       { meaning: "解決する・特定する",                            katakana: "リゾルブ" },
  "reference":     { meaning: "参照",                                        katakana: "リファレンス" },
  "defined":       { meaning: "定義された",                                   katakana: "ディファインド" },
  "fatal":         { meaning: "致命的な",                                     katakana: "フェイタル" },
  "parent":        { meaning: "親（フォルダ階層で一つ上の階層）",               katakana: "ペアレント" },
  "refs":          { meaning: "参照（references の略。Git のブランチ・タグなどへの参照）", katakana: "レフス" },
  "page":          { meaning: "ページ",                                       katakana: "ページ" },
  "internal":      { meaning: "内部の",                                       katakana: "インターナル" },
  "server":        { meaning: "サーバー（データやサービスを提供するコンピューター）", katakana: "サーバー" },
  "forbidden":     { meaning: "禁止された",                                   katakana: "フォビドゥン" },
  "access":        { meaning: "アクセス・接続",                                katakana: "アクセス" },
  "recognized":    { meaning: "認識された",                                   katakana: "レコグナイズド" },
  "external":      { meaning: "外部の",                                       katakana: "エクスターナル" },
  "path":          { meaning: "パス（ファイルやフォルダの場所を示す文字列）",     katakana: "パス" },
  "specified":     { meaning: "指定された",                                   katakana: "スペシファイド" },
  "address":       { meaning: "アドレス（場所を示す番号や文字列）",             katakana: "アドレス" },
  "in use":        { meaning: "使用中",                                       katakana: "イン・ユース" },
  "dependencies":  { meaning: "依存関係（プログラムが必要とする外部のパッケージ群）", katakana: "ディペンデンシーズ" },
  "input":         { meaning: "入力",                                        katakana: "インプット" },
  "maximum":       { meaning: "最大の・最大値",                                katakana: "マキシマム" },
  "stack":         { meaning: "スタック（後入れ先出しのデータ構造）",            katakana: "スタック" },
  "site":          { meaning: "サイト（ウェブサイト）",                         katakana: "サイト" },
  "private":       { meaning: "非公開の・プライベートな",                       katakana: "プライベート" },
  "memory":        { meaning: "メモリ（データを一時的に記憶する場所）",          katakana: "メモリー" },
  "out of":        { meaning: "〜が足りない・〜を使い果たした",                 katakana: "アウト・オブ" },
  "process":       { meaning: "プロセス（実行中のプログラム）",                  katakana: "プロセス" },
  "exit code":     { meaning: "終了コード（プログラムの終了状態を示す数字）",     katakana: "イグジットコード" },

  // ---- バッチ3: ファイル操作編 (2026-06-12 追加) ----
  "already":       { meaning: "既に・もう",                                   katakana: "オールレディ" },
  "replace":       { meaning: "置き換える",                                   katakana: "リプレイス" },
  "copy":          { meaning: "コピーする",                                   katakana: "コピー" },
  "clipboard":     { meaning: "クリップボード（一時的にコピーした内容を保持する場所）", katakana: "クリップボード" },
  "type":          { meaning: "入力する・タイプする",                          katakana: "タイプ" },
  "rename":        { meaning: "名前を変更する",                                katakana: "リネーム" },
  "drag":          { meaning: "ドラッグする・引っ張る",                        katakana: "ドラッグ" },
  "drop":          { meaning: "ドロップする・落とす",                          katakana: "ドロップ" },
  "upload":        { meaning: "アップロードする・送信する",                    katakana: "アップロード" },
  "size":          { meaning: "サイズ・容量",                                 katakana: "サイズ" },
  "unsupported":   { meaning: "サポートされていない・対応していない",           katakana: "アンサポーティッド" },
  "format":        { meaning: "形式・フォーマット",                            katakana: "フォーマット" },
  "choose":        { meaning: "選ぶ・選択する",                                katakana: "チューズ" },
  "location":      { meaning: "場所・位置",                                   katakana: "ロケーション" },
  "read-only":     { meaning: "読み取り専用",                                  katakana: "リードオンリー" },
  "move":          { meaning: "移動する",                                     katakana: "ムーブ" },
  "recycle bin":   { meaning: "ごみ箱",                                       katakana: "リサイクルビン" },
  "compress":      { meaning: "圧縮する",                                     katakana: "コンプレス" },
  "extract":       { meaning: "展開する・取り出す",                            katakana: "エクストラクト" },
  "archive":       { meaning: "アーカイブ・圧縮ファイル",                       katakana: "アーカイブ" },
  "program":       { meaning: "プログラム",                                    katakana: "プログラム" },
  "hidden":        { meaning: "隠れた・非表示の",                              katakana: "ヒドゥン" },
  "too long":      { meaning: "長すぎる",                                     katakana: "トゥーロング" },
  "download":      { meaning: "ダウンロードする",                              katakana: "ダウンロード" },
  "complete":      { meaning: "完了する・完全な",                              katakana: "コンプリート" },
  "open":          { meaning: "開く",                                         katakana: "オープン" },
  "restore":       { meaning: "復元する・元に戻す",                            katakana: "リストア" },
  "empty":         { meaning: "空にする・空の",                                katakana: "エンプティ" },

  // ---- バッチ4: Git/GitHub深掘り編 (2026-06-12 追加) ----
  "ahead":         { meaning: "進んでいる・先にいる",                          katakana: "アヘッド" },
  "commits":       { meaning: "コミット（変更の記録の単位、commit の複数形）",   katakana: "コミッツ" },
  "behind":        { meaning: "遅れている・後ろにいる",                        katakana: "ビハインド" },
  "fast-forward":  { meaning: "早送り（履歴を一直線に進めること）",             katakana: "ファストフォワード" },
  "switch":        { meaning: "切り替える",                                   katakana: "スイッチ" },
  "branches":      { meaning: "ブランチ（branch の複数形）",                   katakana: "ブランチズ" },
  "create":        { meaning: "作成する",                                     katakana: "クリエイト" },
  "fork":          { meaning: "フォークする（リポジトリを自分のアカウントに複製すること）", katakana: "フォーク" },
  "star":          { meaning: "スターをつける・お気に入りに登録する",          katakana: "スター" },
  "watch":         { meaning: "ウォッチする・注目する",                        katakana: "ウォッチ" },
  "notifications": { meaning: "通知",                                        katakana: "ノーティフィケーションズ" },
  "issue":         { meaning: "問題・課題（GitHubではタスクや不具合の管理単位）", katakana: "イシュー" },
  "assign":        { meaning: "割り当てる・任命する",                          katakana: "アサイン" },
  "leave":         { meaning: "残す・置いていく",                              katakana: "リーブ" },
  "review":        { meaning: "レビュー・確認",                               katakana: "レビュー" },
  "approve":       { meaning: "承認する",                                     katakana: "アプルーブ" },
  "request":       { meaning: "依頼する・要求する",                            katakana: "リクエスト" },
  "tag":           { meaning: "タグ（特定のコミットに付ける目印）",             katakana: "タグ" },
  "clone":         { meaning: "クローンする・複製する",                        katakana: "クローン" },

  // ---- バッチ5: Windows/PowerShell編 (2026-06-12 追加) ----
  "currently":     { meaning: "現在・今のところ",                              katakana: "カレントリー" },
  "checking":      { meaning: "確認している",                                  katakana: "チェッキング" },
  "restart":       { meaning: "再起動",                                       katakana: "リスタート" },
  "required":      { meaning: "必要な",                                       katakana: "リクワイアード" },
  "app":           { meaning: "アプリ（application の略）",                    katakana: "アップ" },
  "execution":     { meaning: "実行",                                         katakana: "エクセキューション" },
  "disabled":      { meaning: "無効化された",                                  katakana: "ディセイブルド" },
  "term":          { meaning: "用語・語",                                     katakana: "ターム" },
  "cmdlet":        { meaning: "コマンドレット（PowerShellのコマンドの単位）",    katakana: "コマンドレット" },
  "press":         { meaning: "押す",                                         katakana: "プレス" },
  "continue":      { meaning: "続ける・続行する",                              katakana: "コンティニュー" },
  "requested":     { meaning: "要求された",                                   katakana: "リクエステッド" },
  "elevation":     { meaning: "昇格（管理者権限への切り替え）",                  katakana: "エレベーション" },
  "responding":    { meaning: "応答している",                                  katakana: "レスポンディング" },
  "end":           { meaning: "終了する・終わる",                              katakana: "エンド" },
  "safely":        { meaning: "安全に",                                       katakana: "セーフリー" },
  "eject":         { meaning: "取り出す・排出する",                            katakana: "イジェクト" },
  "ran into":      { meaning: "遭遇した・出くわした",                          katakana: "ランイントゥ" },
  "problem":       { meaning: "問題",                                         katakana: "プロブレム" },
  "default":       { meaning: "既定の・デフォルトの",                          katakana: "デフォルト" },
  "file type":     { meaning: "ファイル形式",                                  katakana: "ファイルタイプ" },
  "features":      { meaning: "機能",                                         katakana: "フィーチャーズ" },
  "on or off":     { meaning: "オンまたはオフ",                                katakana: "オンオアオフ" },
  "plug in":       { meaning: "接続する・差し込む",                            katakana: "プラグイン" },
  "schedule":      { meaning: "予約する・スケジュールする",                    katakana: "スケジュール" },
  "battery":       { meaning: "バッテリー",                                   katakana: "バッテリー" },
  "saver":         { meaning: "節約するもの",                                  katakana: "セイバー" },
  "internet":      { meaning: "インターネット",                                katakana: "インターネット" },
  "meet":          { meaning: "満たす・出会う",                                katakana: "ミート" },
  "requirements":  { meaning: "必要条件・要件",                                katakana: "リクワイアメンツ" },

  // ---- バッチ6: HTML/CSS/JavaScript編 (2026-06-12 追加) ----
  "uncaught":      { meaning: "捕捉されていない（try-catchで処理されていない）", katakana: "アンコート" },
  "null":          { meaning: "null（値が「何もない」ことを示す特別な値）",      katakana: "ヌル" },
  "warning":       { meaning: "警告",                                         katakana: "ワーニング" },
  "unique":        { meaning: "一意の・唯一の",                                katakana: "ユニーク" },
  "resource":      { meaning: "リソース（画像やファイルなどの資源）",            katakana: "リソース" },
  "responded":     { meaning: "応答した",                                     katakana: "レスポンデッド" },
  "fallback":      { meaning: "フォールバック・代替手段",                       katakana: "フォールバック" },
  "font":          { meaning: "フォント・書体",                                katakana: "フォント" },
  "instead":       { meaning: "代わりに",                                     katakana: "インステッド" },
  "expression":    { meaning: "式",                                          katakana: "エクスプレッション" },
  "callable":      { meaning: "呼び出し可能な",                                katakana: "コーラブル" },
  "missing":       { meaning: "欠けている・見つからない",                       katakana: "ミッシング" },
  "alt text":      { meaning: "代替テキスト（画像の説明文）",                   katakana: "オルトテキスト" },
  "accessible":    { meaning: "アクセス可能な",                                katakana: "アクセシブル" },
  "name":          { meaning: "名前",                                         katakana: "ネーム" },
  "displayed":     { meaning: "表示された",                                   katakana: "ディスプレイド" },
  "specify":       { meaning: "指定する",                                     katakana: "スペシファイ" },
  "unit":          { meaning: "単位",                                         katakana: "ユニット" },
  "selector":      { meaning: "セレクタ（CSSでスタイルを適用する対象を指定する記述）", katakana: "セレクタ" },
  "overridden":    { meaning: "上書きされた",                                  katakana: "オーバーリドゥン" },
  "responsive":    { meaning: "レスポンシブな（画面サイズに応じて変化する）",     katakana: "レスポンシブ" },
  "meta tag":      { meaning: "メタタグ（ページの情報を記述するタグ）",          katakana: "メタタグ" },
  "blocked":       { meaning: "ブロックされた",                                katakana: "ブロックド" },
  "policy":        { meaning: "方針・ポリシー",                                katakana: "ポリシー" },
  "mixed":         { meaning: "混在した",                                     katakana: "ミックスド" },
  "insecure":      { meaning: "安全でない",                                   katakana: "インセキュア" },
  "inspect":       { meaning: "検証する・調査する",                            katakana: "インスペクト" },
  "developer tools": { meaning: "開発者ツール",                               katakana: "デベロッパーツール" },
  "never":         { meaning: "一度も〜ない・決して〜ない",                     katakana: "ネバー" },
  "enabled":       { meaning: "有効化された",                                  katakana: "イネイブルド" },
  "refresh":       { meaning: "再読み込みする・更新する",                       katakana: "リフレッシュ" },
  "closed":        { meaning: "閉じられた",                                    katakana: "クローズド" },
};

// 大文字小文字を無視してキーを解決する
function getTerm(key) {
  return terms[key] || terms[key.toLowerCase()] || null;
}
