// ============================================================
// 用語データ（重要単語の意味・カタカナ発音を一元管理）
//
// data.js の各例文の vocabulary は、ここに定義したキーを参照する。
// 同じ単語でも例文によって意味が違う場合は、
// data.js 側で { term: "キー", meaning: "この例文専用の意味" } のように上書きできる。
//
// 新しい単語を追加する時は、ここに1件追記するだけでよい。
// ============================================================

const terms = {
  "permission":    { meaning: "許可・権限",                                   katakana: "パーミッション" },
  "denied":        { meaning: "拒否された（deny の過去分詞）",                  katakana: "デナイド" },
  "such":          { meaning: "そのような",                                   katakana: "サッチ" },
  "directory":     { meaning: "フォルダ（フォルダの技術的な呼び名）",            katakana: "ディレクトリ" },
  "command":       { meaning: "コマンド・命令",                                katakana: "コマンド" },
  "found":         { meaning: "見つかった（find の過去分詞）",                  katakana: "ファウンド" },
  "delete":        { meaning: "削除する",                                     katakana: "デリート" },
  "action":        { meaning: "操作・行動",                                   katakana: "アクション" },
  "undone":        { meaning: "取り消された（undo の過去分詞）",                katakana: "アンダン" },
  "changes":       { meaning: "変更点・差分",                                 katakana: "チェンジズ" },
  "staged":        { meaning: "ステージングされた（コミット準備完了の状態）",     katakana: "ステージド" },
  "commit":        { meaning: "変更を確定して保存すること",                     katakana: "コミット" },
  "working tree":  { meaning: "作業ツリー（現在編集中のファイル群）",            katakana: "ワーキングツリー" },
  "clean":         { meaning: "きれいな・変更なしの状態",                       katakana: "クリーン" },
  "merge":         { meaning: "マージ・統合（2つのブランチを合体させること）",    katakana: "マージ" },
  "conflict":      { meaning: "競合・衝突",                                   katakana: "コンフリクト" },
  "detected":      { meaning: "検出された（detect の過去分詞）",                katakana: "ディテクテッド" },
  "branch":        { meaning: "ブランチ・枝（開発の分岐）",                     katakana: "ブランチ" },
  "up to date":    { meaning: "最新の状態・同期済み",                          katakana: "アップトゥデート" },
  "origin":        { meaning: "リモートリポジトリの別名（通常 GitHub）",         katakana: "オリジン" },
  "pull request":  { meaning: "プルリクエスト（コードのレビュー・統合依頼）",     katakana: "プルリクエスト" },
  "merged":        { meaning: "マージされた・統合された",                       katakana: "マージド" },
  "successfully":  { meaning: "正常に・成功して",                              katakana: "サクセスフリー" },
  "rate limit":    { meaning: "利用制限・レートリミット（単位時間あたりの上限）", katakana: "レートリミット" },
  "exceeded":      { meaning: "超えた・超過した（exceed の過去分詞）",          katakana: "エクシーデッド" },
  "access token":  { meaning: "アクセストークン（認証用の文字列）",              katakana: "アクセストークン" },
  "expired":       { meaning: "期限切れになった（expire の過去分詞）",          katakana: "エクスパイアード" },
  "trust":         { meaning: "信頼する・信用する",                            katakana: "トラスト" },
  "authors":       { meaning: "作成者・著者（author の複数形）",                katakana: "オーサーズ" },
  "unsaved":       { meaning: "保存されていない",                              katakana: "アンセーブド" },
  "lost":          { meaning: "失われた（lose の過去形）",                      katakana: "ロスト" },
  "syntax":        { meaning: "構文・文法（コードのルール）",                    katakana: "シンタックス" },
  "unexpected":    { meaning: "予期しない・予想外の",                           katakana: "アンエクスペクテッド" },
  "token":         { meaning: "トークン（コードの最小単位の記号や単語）",         katakana: "トークン" },
  "properties":    { meaning: "プロパティ・属性（オブジェクトの持つ情報）",       katakana: "プロパティーズ" },
  "undefined":     { meaning: "未定義・値が設定されていない状態",                katakana: "アンディファインド" },
  "extension":     { meaning: "拡張機能（VS Code に追加できる機能）",            katakana: "エクステンション" },
  "incompatible":  { meaning: "互換性がない・相性が悪い",                       katakana: "インコンパティブル" },
  "update":        { meaning: "アップデート・更新",                            katakana: "アップデート" },
  "available":     { meaning: "利用可能な・入手可能な",                         katakana: "アベイラブル" },
  "apply":         { meaning: "適用する",                                     katakana: "アプライ" },
  "session":       { meaning: "セッション（ログイン中の一連の接続期間）",        katakana: "セッション" },
  "invalid":       { meaning: "無効な・不正な",                                katakana: "インバリッド" },
  "credentials":   { meaning: "認証情報（ID やパスワードなど）",                 katakana: "クレデンシャルズ" },
  "allow":         { meaning: "許可する・許す",                                katakana: "アロウ" },
  "run":           { meaning: "実行する・走らせる",                            katakana: "ラン" },
  "matching":      { meaning: "一致する・マッチする",                          katakana: "マッチング" },
  "results":       { meaning: "結果・検索結果",                               katakana: "リザルツ" },
  "connection":    { meaning: "接続・コネクション",                            katakana: "コネクション" },
  "timed out":     { meaning: "タイムアウトした（時間切れになった）",            katakana: "タイムドアウト" },
  "untracked":     { meaning: "追跡されていない・管理されていない",              katakana: "アントラックド" },
  "include":       { meaning: "含める・含む",                                 katakana: "インクルード" },
  "detached":      { meaning: "切り離された・分離された",                       katakana: "デタッチド" },
  "HEAD":          { meaning: "現在チェックアウトしているポイント（Git の用語）", katakana: "ヘッド" },
  "state":         { meaning: "状態",                                        katakana: "ステート" },
  "conversation":  { meaning: "会話・やり取り",                               katakana: "コンバーセーション" },
  "permanently":   { meaning: "永久に・恒久的に",                              katakana: "パーマネントリー" },
  "deleted":       { meaning: "削除された",                                   katakana: "デリーテッド" },
  "limit":         { meaning: "制限・上限",                                   katakana: "リミット" },
  "reached":       { meaning: "達した・到達した（reach の過去形）",             katakana: "リーチト" },
  "fetch":         { meaning: "取得する・取ってくる",                          katakana: "フェッチ" },
  "failed":        { meaning: "失敗した（fail の過去形）",                      katakana: "フェイルド" },
  "push":          { meaning: "プッシュ（ローカルの変更をリモートに送ること）",   katakana: "プッシュ" },
  "repository":    { meaning: "リポジトリ（コードの保管場所）",                  katakana: "リポジトリ" },
  "uncommitted":   { meaning: "未コミットの・まだ確定されていない",              katakana: "アンコミッテッド" },
  "stash":         { meaning: "スタッシュ（変更を一時的に退避させること）",       katakana: "スタッシュ" },
  "overwrite":     { meaning: "上書きする",                                   katakana: "オーバーライト" },
  "existing":      { meaning: "既存の・現在ある",                              katakana: "イグジスティング" },

  // ---- バッチ2: エラーメッセージ編 (2026-06-12 追加) ----
  "module":        { meaning: "モジュール（プログラムの部品・構成要素）",        katakana: "モジュール" },
  "resolve":       { meaning: "解決する・特定する",                            katakana: "リゾルブ" },
  "reference":     { meaning: "参照",                                        katakana: "リファレンス" },
  "defined":       { meaning: "定義された",                                   katakana: "ディファインド" },
  "fatal":         { meaning: "致命的な",                                     katakana: "フェイタル" },
  "parent":        { meaning: "親（フォルダ階層で一つ上の階層）",               katakana: "ペアレント" },
  "refs":          { meaning: "参照（references の略。Git のブランチ・タグなどへの参照）", katakana: "レフス" },
  "page":          { meaning: "ページ",                                       katakana: "ページ" },
  "internal":      { meaning: "内部の",                                       katakana: "インターナル" },
  "server":        { meaning: "サーバー（データやサービスを提供するコンピューター）", katakana: "サーバー" },
  "forbidden":     { meaning: "禁止された",                                   katakana: "フォビドゥン" },
  "access":        { meaning: "アクセス・接続",                                katakana: "アクセス" },
  "recognized":    { meaning: "認識された",                                   katakana: "レコグナイズド" },
  "external":      { meaning: "外部の",                                       katakana: "エクスターナル" },
  "path":          { meaning: "パス（ファイルやフォルダの場所を示す文字列）",     katakana: "パス" },
  "specified":     { meaning: "指定された",                                   katakana: "スペシファイド" },
  "address":       { meaning: "アドレス（場所を示す番号や文字列）",             katakana: "アドレス" },
  "in use":        { meaning: "使用中",                                       katakana: "イン・ユース" },
  "dependencies":  { meaning: "依存関係（プログラムが必要とする外部のパッケージ群）", katakana: "ディペンデンシーズ" },
  "input":         { meaning: "入力",                                        katakana: "インプット" },
  "maximum":       { meaning: "最大の・最大値",                                katakana: "マキシマム" },
  "stack":         { meaning: "スタック（後入れ先出しのデータ構造）",            katakana: "スタック" },
  "site":          { meaning: "サイト（ウェブサイト）",                         katakana: "サイト" },
  "private":       { meaning: "非公開の・プライベートな",                       katakana: "プライベート" },
  "memory":        { meaning: "メモリ（データを一時的に記憶する場所）",          katakana: "メモリー" },
  "out of":        { meaning: "〜が足りない・〜を使い果たした",                 katakana: "アウト・オブ" },
  "process":       { meaning: "プロセス（実行中のプログラム）",                  katakana: "プロセス" },
  "exit code":     { meaning: "終了コード（プログラムの終了状態を示す数字）",     katakana: "イグジットコード" },

  // ---- バッチ3: ファイル操作編 (2026-06-12 追加) ----
  "already":       { meaning: "既に・もう",                                   katakana: "オールレディ" },
  "replace":       { meaning: "置き換える",                                   katakana: "リプレイス" },
  "copy":          { meaning: "コピーする",                                   katakana: "コピー" },
  "clipboard":     { meaning: "クリップボード（一時的にコピーした内容を保持する場所）", katakana: "クリップボード" },
  "type":          { meaning: "入力する・タイプする",                          katakana: "タイプ" },
  "rename":        { meaning: "名前を変更する",                                katakana: "リネーム" },
  "drag":          { meaning: "ドラッグする・引っ張る",                        katakana: "ドラッグ" },
  "drop":          { meaning: "ドロップする・落とす",                          katakana: "ドロップ" },
  "upload":        { meaning: "アップロードする・送信する",                    katakana: "アップロード" },
  "size":          { meaning: "サイズ・容量",                                 katakana: "サイズ" },
  "unsupported":   { meaning: "サポートされていない・対応していない",           katakana: "アンサポーティッド" },
  "format":        { meaning: "形式・フォーマット",                            katakana: "フォーマット" },
  "choose":        { meaning: "選ぶ・選択する",                                katakana: "チューズ" },
  "location":      { meaning: "場所・位置",                                   katakana: "ロケーション" },
  "read-only":     { meaning: "読み取り専用",                                  katakana: "リードオンリー" },
  "move":          { meaning: "移動する",                                     katakana: "ムーブ" },
  "recycle bin":   { meaning: "ごみ箱",                                       katakana: "リサイクルビン" },
  "compress":      { meaning: "圧縮する",                                     katakana: "コンプレス" },
  "extract":       { meaning: "展開する・取り出す",                            katakana: "エクストラクト" },
  "archive":       { meaning: "アーカイブ・圧縮ファイル",                       katakana: "アーカイブ" },
  "program":       { meaning: "プログラム",                                    katakana: "プログラム" },
  "hidden":        { meaning: "隠れた・非表示の",                              katakana: "ヒドゥン" },
  "too long":      { meaning: "長すぎる",                                     katakana: "トゥーロング" },
  "download":      { meaning: "ダウンロードする",                              katakana: "ダウンロード" },
  "complete":      { meaning: "完了する・完全な",                              katakana: "コンプリート" },
  "open":          { meaning: "開く",                                         katakana: "オープン" },
  "restore":       { meaning: "復元する・元に戻す",                            katakana: "リストア" },
  "empty":         { meaning: "空にする・空の",                                katakana: "エンプティ" },

  // ---- バッチ4: Git/GitHub深掘り編 (2026-06-12 追加) ----
  "ahead":         { meaning: "進んでいる・先にいる",                          katakana: "アヘッド" },
  "commits":       { meaning: "コミット（変更の記録の単位、commit の複数形）",   katakana: "コミッツ" },
  "behind":        { meaning: "遅れている・後ろにいる",                        katakana: "ビハインド" },
  "fast-forward":  { meaning: "早送り（履歴を一直線に進めること）",             katakana: "ファストフォワード" },
  "switch":        { meaning: "切り替える",                                   katakana: "スイッチ" },
  "branches":      { meaning: "ブランチ（branch の複数形）",                   katakana: "ブランチズ" },
  "create":        { meaning: "作成する",                                     katakana: "クリエイト" },
  "fork":          { meaning: "フォークする（リポジトリを自分のアカウントに複製すること）", katakana: "フォーク" },
  "star":          { meaning: "スターをつける・お気に入りに登録する",          katakana: "スター" },
  "watch":         { meaning: "ウォッチする・注目する",                        katakana: "ウォッチ" },
  "notifications": { meaning: "通知",                                        katakana: "ノーティフィケーションズ" },
  "issue":         { meaning: "問題・課題（GitHubではタスクや不具合の管理単位）", katakana: "イシュー" },
  "assign":        { meaning: "割り当てる・任命する",                          katakana: "アサイン" },
  "leave":         { meaning: "残す・置いていく",                              katakana: "リーブ" },
  "review":        { meaning: "レビュー・確認",                               katakana: "レビュー" },
  "approve":       { meaning: "承認する",                                     katakana: "アプルーブ" },
  "request":       { meaning: "依頼する・要求する",                            katakana: "リクエスト" },
  "tag":           { meaning: "タグ（特定のコミットに付ける目印）",             katakana: "タグ" },
  "clone":         { meaning: "クローンする・複製する",                        katakana: "クローン" },

  // ---- バッチ5: Windows/PowerShell編 (2026-06-12 追加) ----
  "currently":     { meaning: "現在・今のところ",                              katakana: "カレントリー" },
  "checking":      { meaning: "確認している",                                  katakana: "チェッキング" },
  "restart":       { meaning: "再起動",                                       katakana: "リスタート" },
  "required":      { meaning: "必要な",                                       katakana: "リクワイアード" },
  "app":           { meaning: "アプリ（application の略）",                    katakana: "アップ" },
  "execution":     { meaning: "実行",                                         katakana: "エクセキューション" },
  "disabled":      { meaning: "無効化された",                                  katakana: "ディセイブルド" },
  "term":          { meaning: "用語・語",                                     katakana: "ターム" },
  "cmdlet":        { meaning: "コマンドレット（PowerShellのコマンドの単位）",    katakana: "コマンドレット" },
  "press":         { meaning: "押す",                                         katakana: "プレス" },
  "continue":      { meaning: "続ける・続行する",                              katakana: "コンティニュー" },
  "requested":     { meaning: "要求された",                                   katakana: "リクエステッド" },
  "elevation":     { meaning: "昇格（管理者権限への切り替え）",                  katakana: "エレベーション" },
  "responding":    { meaning: "応答している",                                  katakana: "レスポンディング" },
  "end":           { meaning: "終了する・終わる",                              katakana: "エンド" },
  "safely":        { meaning: "安全に",                                       katakana: "セーフリー" },
  "eject":         { meaning: "取り出す・排出する",                            katakana: "イジェクト" },
  "ran into":      { meaning: "遭遇した・出くわした",                          katakana: "ランイントゥ" },
  "problem":       { meaning: "問題",                                         katakana: "プロブレム" },
  "default":       { meaning: "既定の・デフォルトの",                          katakana: "デフォルト" },
  "file type":     { meaning: "ファイル形式",                                  katakana: "ファイルタイプ" },
  "features":      { meaning: "機能",                                         katakana: "フィーチャーズ" },
  "on or off":     { meaning: "オンまたはオフ",                                katakana: "オンオアオフ" },
  "plug in":       { meaning: "接続する・差し込む",                            katakana: "プラグイン" },
  "schedule":      { meaning: "予約する・スケジュールする",                    katakana: "スケジュール" },
  "battery":       { meaning: "バッテリー",                                   katakana: "バッテリー" },
  "saver":         { meaning: "節約するもの",                                  katakana: "セイバー" },
  "internet":      { meaning: "インターネット",                                katakana: "インターネット" },
  "meet":          { meaning: "満たす・出会う",                                katakana: "ミート" },
  "requirements":  { meaning: "必要条件・要件",                                katakana: "リクワイアメンツ" },

  // ---- バッチ6: HTML/CSS/JavaScript編 (2026-06-12 追加) ----
  "uncaught":      { meaning: "捕捉されていない（try-catchで処理されていない）", katakana: "アンコート" },
  "null":          { meaning: "null（値が「何もない」ことを示す特別な値）",      katakana: "ヌル" },
  "warning":       { meaning: "警告",                                         katakana: "ワーニング" },
  "unique":        { meaning: "一意の・唯一の",                                katakana: "ユニーク" },
  "resource":      { meaning: "リソース（画像やファイルなどの資源）",            katakana: "リソース" },
  "responded":     { meaning: "応答した",                                     katakana: "レスポンデッド" },
  "fallback":      { meaning: "フォールバック・代替手段",                       katakana: "フォールバック" },
  "font":          { meaning: "フォント・書体",                                katakana: "フォント" },
  "instead":       { meaning: "代わりに",                                     katakana: "インステッド" },
  "expression":    { meaning: "式",                                          katakana: "エクスプレッション" },
  "callable":      { meaning: "呼び出し可能な",                                katakana: "コーラブル" },
  "missing":       { meaning: "欠けている・見つからない",                       katakana: "ミッシング" },
  "alt text":      { meaning: "代替テキスト（画像の説明文）",                   katakana: "オルトテキスト" },
  "accessible":    { meaning: "アクセス可能な",                                katakana: "アクセシブル" },
  "name":          { meaning: "名前",                                         katakana: "ネーム" },
  "displayed":     { meaning: "表示された",                                   katakana: "ディスプレイド" },
  "specify":       { meaning: "指定する",                                     katakana: "スペシファイ" },
  "unit":          { meaning: "単位",                                         katakana: "ユニット" },
  "selector":      { meaning: "セレクタ（CSSでスタイルを適用する対象を指定する記述）", katakana: "セレクタ" },
  "overridden":    { meaning: "上書きされた",                                  katakana: "オーバーリドゥン" },
  "responsive":    { meaning: "レスポンシブな（画面サイズに応じて変化する）",     katakana: "レスポンシブ" },
  "meta tag":      { meaning: "メタタグ（ページの情報を記述するタグ）",          katakana: "メタタグ" },
  "blocked":       { meaning: "ブロックされた",                                katakana: "ブロックド" },
  "policy":        { meaning: "方針・ポリシー",                                katakana: "ポリシー" },
  "mixed":         { meaning: "混在した",                                     katakana: "ミックスド" },
  "insecure":      { meaning: "安全でない",                                   katakana: "インセキュア" },
  "inspect":       { meaning: "検証する・調査する",                            katakana: "インスペクト" },
  "developer tools": { meaning: "開発者ツール",                               katakana: "デベロッパーツール" },
  "never":         { meaning: "一度も〜ない・決して〜ない",                     katakana: "ネバー" },
  "enabled":       { meaning: "有効化された",                                  katakana: "イネイブルド" },
  "refresh":       { meaning: "再読み込みする・更新する",                       katakana: "リフレッシュ" },
  "closed":        { meaning: "閉じられた",                                    katakana: "クローズド" },

  // ---- バッチ7: AIツール編 (2026-06-13 追加) ----
  "thinking":      { meaning: "考えている",                                    katakana: "シンキング" },
  "stop":          { meaning: "停止する・止める",                              katakana: "ストップ" },
  "generating":    { meaning: "生成している",                                  katakana: "ジェネレーティング" },
  "regenerate":    { meaning: "再生成する",                                    katakana: "リジェネレート" },
  "response":      { meaning: "応答・返答",                                    katakana: "レスポンス" },
  "usage":         { meaning: "使用量・利用",                                  katakana: "ユーセージ" },
  "model":         { meaning: "モデル（AIの学習済みモデル）",                    katakana: "モデル" },
  "chat":          { meaning: "チャット・会話",                                katakana: "チャット" },
  "code":          { meaning: "コード（プログラムの記述）",                      katakana: "コード" },
  "edit":          { meaning: "編集する",                                      katakana: "エディット" },
  "message":       { meaning: "メッセージ・伝言",                              katakana: "メッセージ" },
  "clear":         { meaning: "消去する・クリアする",                          katakana: "クリア" },
  "history":       { meaning: "履歴",                                         katakana: "ヒストリー" },
  "content":       { meaning: "内容・コンテンツ",                              katakana: "コンテンツ" },
  "incorrect":     { meaning: "間違っている・不正確な",                         katakana: "インコレクト" },
  "share":         { meaning: "共有する",                                      katakana: "シェア" },
  "upgrade":       { meaning: "アップグレードする",                            katakana: "アップグレード" },
  "real-time":     { meaning: "リアルタイムの・即時の",                         katakana: "リアルタイム" },
  "information":   { meaning: "情報",                                         katakana: "インフォメーション" },
  "something":     { meaning: "何か",                                         katakana: "サムシング" },
  "wrong":         { meaning: "間違った・おかしい",                            katakana: "ロング" },
  "try again":     { meaning: "もう一度試す",                                  katakana: "トライアゲイン" },
  "flagged":       { meaning: "フラグが立てられた（確認対象として印が付けられた）", katakana: "フラッグド" },
  "rate":          { meaning: "評価する",                                      katakana: "レート" },
  "length":        { meaning: "長さ",                                         katakana: "レングス" },

  // ---- バッチ8: パッケージ管理(npm)編 (2026-06-13 追加) ----
  "deprecated":    { meaning: "非推奨の（過去分詞）",                          katakana: "デプリケイテッド" },
  "maintained":    { meaning: "保守されている（過去分詞）",                     katakana: "メインテインド" },
  "vulnerabilities": { meaning: "脆弱性（複数形）",                             katakana: "バルネラビリティーズ" },
  "moderate":      { meaning: "中程度の",                                      katakana: "モデレート" },
  "audit":         { meaning: "監査する・検査する",                            katakana: "オーディット" },
  "fix":           { meaning: "修正する",                                      katakana: "フィックス" },
  "package":       { meaning: "パッケージ（再利用可能なコードのまとまり）",       katakana: "パッケージ" },
  "dependency":    { meaning: "依存関係（単数形）",                            katakana: "ディペンデンシー" },
  "dependencies":  { meaning: "依存パッケージ群（複数形）",                     katakana: "ディペンデンシーズ" },
  "script":        { meaning: "スクリプト（一連のコマンド）",                    katakana: "スクリプト" },
  "install":       { meaning: "インストールする・導入する",                     katakana: "インストール" },
  "out of date":   { meaning: "古くなっている・最新でない",                     katakana: "アウトオブデート" },
  "version":       { meaning: "バージョン・版",                                katakana: "バージョン" },
  "detected":      { meaning: "検出された",                                    katakana: "ディテクテッド" },
  "uninstall":     { meaning: "アンインストールする・削除する",                  katakana: "アンインストール" },
  "successfully":  { meaning: "正常に・うまく",                                katakana: "サクセスフリー" },
  "requires":      { meaning: "〜を必要とする（三単現）",                        katakana: "リクワイアズ" },
  "higher":        { meaning: "より高い（highの比較級）",                       katakana: "ハイヤー" },
  "cache":         { meaning: "キャッシュ（一時保存データ）",                    katakana: "キャッシュ" },
  "outdated":      { meaning: "期限切れの・古くなった",                         katakana: "アウトデイテッド" },
  "large":         { meaning: "大きい",                                       katakana: "ラージ" },
  "folder":        { meaning: "フォルダ・ディレクトリ",                         katakana: "フォルダ" },
  "take effect":   { meaning: "効果を持つ・発効する",                          katakana: "テイクエフェクト" },

  // ---- バッチ9: ブラウザ開発者ツール編 (2026-06-13 追加) ----
  "console":       { meaning: "コンソール（ログ・エラーが表示される画面）",       katakana: "コンソール" },
  "properties":    { meaning: "プロパティ・属性（複数形）",                     katakana: "プロパティーズ" },
  "breakpoint":    { meaning: "ブレークポイント（処理を一時停止する地点）",       katakana: "ブレークポイント" },
  "pause":         { meaning: "一時停止する",                                  katakana: "ポーズ" },
  "step":          { meaning: "ステップ（1段階ずつ進める操作）",                 katakana: "ステップ" },
  "cookie":        { meaning: "クッキー（サイトが保存する小さなデータ）",          katakana: "クッキー" },
  "view":          { meaning: "見る・表示する",                                katakana: "ビュー" },
  "source":        { meaning: "源・元（ソースコードなど）",                      katakana: "ソース" },
  "enable":        { meaning: "可能にする・有効にする",                         katakana: "イネーブル" },
  "reload":        { meaning: "再読み込みする",                                katakana: "リロード" },
  "network":       { meaning: "ネットワーク・通信網",                           katakana: "ネットワーク" },
  "request":       { meaning: "要求・リクエスト",                              katakana: "リクエスト" },
  "simulate":      { meaning: "模擬的に再現する・シミュレートする",               katakana: "シミュレート" },
  "slow":          { meaning: "遅い",                                         katakana: "スロー" },
  "local":         { meaning: "地元の・その場所の",                             katakana: "ローカル" },
  "storage":       { meaning: "保管・ストレージ",                              katakana: "ストレージ" },
  "right-click":   { meaning: "右クリックする",                                katakana: "ライトクリック" },
  "select":        { meaning: "選択する",                                      katakana: "セレクト" },
  "check":         { meaning: "確認する",                                      katakana: "チェック" },
  "details":       { meaning: "詳細情報（複数形）",                            katakana: "ディテールズ" },
  "exception":     { meaning: "例外（単数形）",                                katakana: "イクセプション" },
  "exceptions":    { meaning: "例外（複数形）",                                katakana: "イクセプションズ" },
  "handled":       { meaning: "処理された（handleの過去分詞）",                 katakana: "ハンドルド" },
  "debugging":     { meaning: "デバッグしている（不具合を取り除いている）",       katakana: "デバッギング" },
  "step by step":  { meaning: "一歩ずつ・少しずつ",                             katakana: "ステップバイステップ" },

  // ---- バッチ10: Gitブランチ・履歴操作編 (2026-06-13 追加) ----
  "checkout":      { meaning: "チェックアウトする（作業対象のブランチを切り替える）", katakana: "チェックアウト" },
  "pull":          { meaning: "プル（リモートの変更を取得して反映すること）",     katakana: "プル" },
  "remote":        { meaning: "リモート（遠隔のリポジトリ）",                    katakana: "リモート" },
  "latest":        { meaning: "最新の",                                       katakana: "レイテスト" },
  "diff":          { meaning: "差分（変更内容の違い）",                         katakana: "ディフ" },
  "revert":        { meaning: "元に戻す（取り消すコミットを作成する）",           katakana: "リバート" },
  "amend":         { meaning: "修正する・改める",                              katakana: "アメンド" },
  "squash":        { meaning: "押しつぶす・まとめる",                          katakana: "スカッシュ" },
  "cherry-pick":   { meaning: "他のブランチから特定のコミットだけ取り込む",       katakana: "チェリーピック" },
  "modified":      { meaning: "変更された（modifyの過去分詞）",                 katakana: "モディファイド" },
  "blame":         { meaning: "誰がいつ変更したかを調べる",                      katakana: "ブレイム" },
  "without":       { meaning: "〜なしで",                                     katakana: "ウィズアウト" },
  "diverged":      { meaning: "分岐した（divergeの過去分詞）",                  katakana: "ダイバージド" },
  "force":         { meaning: "力・強制する",                                  katakana: "フォース" },
  "caution":       { meaning: "注意・警告",                                    katakana: "コーション" },

  // ---- バッチ11: AIプロンプト・機能編 (2026-06-13 追加) ----
  "prompt":        { meaning: "プロンプト（AIへの指示文）",                     katakana: "プロンプト" },
  "attach":        { meaning: "添付する・取り付ける",                          katakana: "アタッチ" },
  "generate":      { meaning: "生成する",                                      katakana: "ジェネレート" },
  "image":         { meaning: "画像・イメージ",                                katakana: "イメージ" },
  "voice":         { meaning: "声・ボイス",                                    katakana: "ボイス" },
  "search":        { meaning: "検索する",                                      katakana: "サーチ" },
  "summarize":     { meaning: "要約する",                                      katakana: "サマライズ" },
  "translate":     { meaning: "翻訳する",                                      katakana: "トランスレート" },
  "tone":          { meaning: "トーン・言葉遣いの雰囲気",                       katakana: "トーン" },
  "instructions":  { meaning: "指示事項・取扱説明（複数形）",                    katakana: "インストラクションズ" },
  "custom":        { meaning: "特別注文の・カスタムの",                         katakana: "カスタム" },
  "context":       { meaning: "文脈",                                         katakana: "コンテキスト" },
  "window":        { meaning: "窓・一定の範囲",                                katakana: "ウィンドウ" },
  "hallucinate":   { meaning: "（AIが）事実でない情報を生成する",                 katakana: "ハルシネート" },
  "facts":         { meaning: "事実（複数形）",                                katakana: "ファクツ" },
  "draft":         { meaning: "下書き・草案",                                  katakana: "ドラフト" },
  "bullet":        { meaning: "箇条書きの記号",                                katakana: "バレット" },
  "paste":         { meaning: "貼り付ける",                                    katakana: "ペースト" },
  "aloud":         { meaning: "声に出して",                                    katakana: "アラウド" },

  // ---- バッチ12: VS Codeエディタ操作編 (2026-06-13 追加) ----
  "snippet":       { meaning: "スニペット（再利用可能な短いコード）",            katakana: "スニペット" },
  "indent":        { meaning: "インデント・字下げ",                            katakana: "インデント" },
  "cursor":        { meaning: "カーソル（入力位置を示す印）",                    katakana: "カーソル" },
  "multiple":      { meaning: "複数の",                                       katakana: "マルティプル" },
  "split":         { meaning: "分割する",                                      katakana: "スプリット" },
  "columns":       { meaning: "列（複数形）",                                   katakana: "カラムズ" },
  "palette":       { meaning: "パレット（コマンド一覧から選べる場所）",          katakana: "パレット" },
  "keybindings":   { meaning: "キーの割り当て（キーボードショートカット）",       katakana: "キーバインディングズ" },
  "theme":         { meaning: "テーマ・配色デザイン",                          katakana: "テーマ" },
  "zoom":          { meaning: "拡大・縮小する",                                katakana: "ズーム" },
  "line":          { meaning: "行・線",                                       katakana: "ライン" },
  "wrap":          { meaning: "包む・折り返す",                                katakana: "ラップ" },
  "toggle":        { meaning: "オンとオフを切り替える",                         katakana: "トグル" },
  "find":          { meaning: "見つける・検索する",                            katakana: "ファインド" },
  "highlight":     { meaning: "強調する・目立たせる",                          katakana: "ハイライト" },
  "fold":          { meaning: "折りたたむ",                                    katakana: "フォールド" },
  "outline":       { meaning: "輪郭・概要（全体の構成）",                       katakana: "アウトライン" },
  "sidebar":       { meaning: "サイドバー（画面側面の表示領域）",                katakana: "サイドバー" },
  "panel":         { meaning: "パネル・操作盤",                                katakana: "パネル" },
  "tab":           { meaning: "タブ（ファイルの見出し）",                       katakana: "タブ" },
  "workspace":     { meaning: "ワークスペース（作業空間）",                     katakana: "ワークスペース" },

  // ---- バッチ13: ターミナル基本コマンド編 (2026-06-13 追加) ----
  "list":          { meaning: "一覧表示する",                                  katakana: "リスト" },
  "home":          { meaning: "ホーム（ユーザー専用のフォルダ）",                katakana: "ホーム" },
  "remove":        { meaning: "取り除く・削除する",                            katakana: "リムーブ" },
  "permanently":   { meaning: "永久に・完全に",                                katakana: "パーマネントリー" },
  "argument":      { meaning: "引数（コマンドや関数に渡す値）",                  katakana: "アーギュメント" },
  "optional":      { meaning: "省略可能な・任意の",                            katakana: "オプショナル" },
  "flag":          { meaning: "フラグ（目印として付ける指定）",                  katakana: "フラグ" },
  "options":       { meaning: "設定項目一覧（複数形）",                         katakana: "オプションズ" },
  "output":        { meaning: "出力",                                         katakana: "アウトプット" },
  "redirect":      { meaning: "向きを変える・転送する",                         katakana: "リダイレクト" },
  "exit":          { meaning: "終了する・出口",                                katakana: "イグジット" },
  "environment":   { meaning: "環境",                                         katakana: "エンバイロメント" },
  "variable":      { meaning: "変数",                                         katakana: "バリアブル" },
  "administrator": { meaning: "管理者",                                       katakana: "アドミニストレーター" },
  "privileges":    { meaning: "特権・権限（複数形）",                          katakana: "プリビレッジズ" },
  "alias":         { meaning: "エイリアス・別名",                              katakana: "エイリアス" },
  "shell":         { meaning: "シェル（コマンドを実行するプログラム）",          katakana: "シェル" },
  "kill":          { meaning: "強制終了する",                                   katakana: "キル" },
  "print":         { meaning: "画面に表示する・印刷する",                       katakana: "プリント" },
  "working":       { meaning: "作業中の",                                      katakana: "ワーキング" },
  "executable":    { meaning: "実行可能な",                                    katakana: "エクゼキュータブル" },
  "pipe":          { meaning: "パイプ（データの流れをつなぐ仕組み）",            katakana: "パイプ" },

  // ---- バッチ14: GitHub PR・CI/CD編 (2026-06-13 追加) ----
  "label":         { meaning: "ラベル・札（分類のための印）",                    katakana: "レーベル" },
  "milestone":     { meaning: "マイルストーン（重要な節目・目標地点）",          katakana: "マイルストーン" },
  "workflow":      { meaning: "ワークフロー（作業の流れ・手順）",                katakana: "ワークフロー" },
  "build":         { meaning: "ビルド（ソースコードを実行可能な形式に変換する作業）", katakana: "ビルド" },
  "in progress":   { meaning: "進行中",                                       katakana: "イン・プログレス" },
  "test":          { meaning: "テスト・試験",                                  katakana: "テスト" },
  "passed":        { meaning: "合格した（passの過去形）",                       katakana: "パスド" },
  "deploy":        { meaning: "展開する・配備する（本番環境に反映する）",         katakana: "デプロイ" },
  "production":    { meaning: "本番環境",                                      katakana: "プロダクション" },
  "status":        { meaning: "状態・状況",                                    katakana: "ステータス" },
  "checks":        { meaning: "確認項目（複数形）",                            katakana: "チェックス" },
  "comment":       { meaning: "コメント・注釈",                                katakana: "コメント" },
  "mention":       { meaning: "言及する・名前を出す",                          katakana: "メンション" },
  "notification":  { meaning: "通知",                                         katakana: "ノーティフィケーション" },
  "description":   { meaning: "説明・記述",                                    katakana: "ディスクリプション" },
  "template":      { meaning: "テンプレート・型",                              katakana: "テンプレート" },
  "reviewer":      { meaning: "レビュアー（確認する人）",                       katakana: "レビュアー" },
  "pending":       { meaning: "保留中の・未決定の",                            katakana: "ペンディング" },
  "approval":      { meaning: "承認",                                         katakana: "アプルーバル" },
  "close":         { meaning: "閉じる",                                       katakana: "クローズ" },

  // ---- バッチ15: Windows設定・通知編 (2026-06-13 追加) ----
  "volume":        { meaning: "音量",                                         katakana: "ボリューム" },
  "brightness":    { meaning: "明るさ・輝度",                                  katakana: "ブライトネス" },
  "display":       { meaning: "表示する・画面",                                katakana: "ディスプレイ" },
  "pin":           { meaning: "ピン留めする",                                  katakana: "ピン" },
  "taskbar":       { meaning: "タスクバー（画面下部の操作帯）",                  katakana: "タスクバー" },
  "shortcut":      { meaning: "ショートカット（近道・素早くアクセスする手段）",    katakana: "ショートカット" },
  "sleep":         { meaning: "スリープ（省電力の待機状態）",                    katakana: "スリープ" },
  "sign out":      { meaning: "サインアウトする・ログアウトする",                katakana: "サインアウト" },
  "account":       { meaning: "アカウント・利用権",                            katakana: "アカウント" },
  "printer":       { meaning: "プリンター・印刷機",                            katakana: "プリンター" },
  "driver":        { meaning: "ドライバー（ハードウェアを操作するソフトウェア）",  katakana: "ドライバー" },
  "graphics":      { meaning: "グラフィック・画像処理",                         katakana: "グラフィックス" },
  "firewall":      { meaning: "ファイアウォール（防火壁・不正アクセスを防ぐ仕組み）", katakana: "ファイアウォール" },
  "sync":          { meaning: "同期する",                                      katakana: "シンク" },
  "lock":          { meaning: "ロックする・鍵をかける",                         katakana: "ロック" },
  "wallpaper":     { meaning: "壁紙",                                         katakana: "ウォールペーパー" },
  "microphone":    { meaning: "マイク（音声入力装置）",                         katakana: "マイクロフォン" },
  "bluetooth":     { meaning: "Bluetooth（近距離無線通信規格）",                 katakana: "ブルートゥース" },
  "airplane":      { meaning: "飛行機",                                       katakana: "エアプレーン" },
  "manage":        { meaning: "管理する",                                      katakana: "マネージ" },
  "shut down":     { meaning: "完全に電源を切る",                              katakana: "シャットダウン" },

  // ---- バッチ16: JavaScript配列・CSSレイアウト編 (2026-06-13 追加) ----
  "array":         { meaning: "配列（複数の値をまとめて並べたデータ構造）",       katakana: "アレイ" },
  "loop":          { meaning: "ループ（同じ処理を繰り返すこと）",                katakana: "ループ" },
  "map":           { meaning: "対応づける・各要素を変換する",                    katakana: "マップ" },
  "transform":     { meaning: "変形する・変換する",                            katakana: "トランスフォーム" },
  "element":       { meaning: "要素・成分",                                    katakana: "エレメント" },
  "filter":        { meaning: "条件に合うものだけを取り出す",                    katakana: "フィルター" },
  "single":        { meaning: "単一の・1つの",                                 katakana: "シングル" },
  "pop":           { meaning: "配列の最後の要素を取り除く",                      katakana: "ポップ" },
  "function":      { meaning: "機能・関数",                                    katakana: "ファンクション" },
  "return":        { meaning: "戻る・返す",                                    katakana: "リターン" },
  "object":        { meaning: "物・対象（オブジェクト）",                       katakana: "オブジェクト" },
  "property":      { meaning: "プロパティ・属性（オブジェクトが持つ値）",         katakana: "プロパティ" },
  "flexbox":       { meaning: "Flexbox（柔軟に要素を整列させるCSSレイアウト手法）", katakana: "フレックスボックス" },
  "align":         { meaning: "並べる・整列させる",                            katakana: "アライン" },
  "grid":          { meaning: "格子・グリッド",                                katakana: "グリッド" },
  "layout":        { meaning: "配置・レイアウト",                              katakana: "レイアウト" },
  "margin":        { meaning: "マージン・要素の外側の余白",                      katakana: "マージン" },
  "padding":       { meaning: "パディング・要素の内側の余白",                    katakana: "パディング" },
  "border":        { meaning: "境界・枠線",                                    katakana: "ボーダー" },
  "hover":         { meaning: "ホバーする（マウスを上に置く）",                  katakana: "ホバー" },
  "effect":        { meaning: "効果",                                         katakana: "エフェクト" },
  "animate":       { meaning: "動かす・アニメーションさせる",                    katakana: "アニメート" },
  "transition":    { meaning: "移行・推移（状態の変化）",                       katakana: "トランジション" },
  "class":         { meaning: "クラス（種類・部類）",                          katakana: "クラス" },
  "attribute":     { meaning: "属性・特質",                                    katakana: "アトリビュート" },
  "center":        { meaning: "中心・中央に置く",                              katakana: "センター" },
  "auto":          { meaning: "自動の",                                       katakana: "オート" },
};

// 大文字小文字を無視してキーを解決する
function getTerm(key) {
  return terms[key] || terms[key.toLowerCase()] || null;
}
